### ISSUE TITLE
Обновить ссылку

### ISSUE THREAD

**Issue by d47081** [ygguser/simple_sites_directory#1]
Приветствую!

Долгая история, но в связи с переименованием, нужно изменить адрес ссылки

То есть сократить зеркало опеннет, но получаю след. сообщение:
```
The catalog does not contain a site with the address http://[201:23b4:991a:634d:8359:4521:5576:15b7]/opennet/www
```

Можно подправить как то, не охота создавать новую ссылку, ведь старая будет висеть как 404 долгое время..

**Comment by ygguser** [comment]
Done
