### ISSUE TITLE
The domain name cannot be resolved error

### ISSUE THREAD

**Issue by d47081** [ygguser/simple_sites_directory#2]
Trying to change existing record by providing `yo.ygg` domain and get following error:

```
The domain name cannot be resolved, it may not be registered yet or it is not an [ALFIS](https://github.com/Revertron/Alfis) domain name. Please correct it or don't specify it.
```

tried with `http://` prefix, but nothing helps

**Comment by ygguser** [comment]
The resolver cannot resolve yo.ygg. Are you sure that the block has been added to the blockchain and confirmed by other nodes?

`dig AAAA @302:db60::53 yo.ygg +short` returns a void.
