### ISSUE TITLE
RSS notifications not work

### ISSUE THREAD

**Issue by d47081** [ygguser/simple_sites_directory#8]
Just found that missed last updates on main page subscription, that's strange, maybe my local client bug.

is last few website notifications have sent to others?

upd. yes feed not updated for some reasons, it worked before

**Comment by ygguser** [comment]
I don't know how it happened, but for some reason, since December 23, the contents of the scripts for generating html and RSS were the same, i.e., html generation occurred twice... 🤷‍♂️
I returned the contents of the RSS generation script to what it should be... 
Everything should be OK now.

**Comment by ygguser** [comment]
It was my mistake...
Accidentally overwritten the file.
